version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080

  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./.caddy:/root/.caddy
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app